#not working: conduit, sea pickle, ender chest, glow lichen, red mushroom
#format: mrgb.
# m is meta info, add 4 for emissive blocks, 2 for translucent blocks, 1 for opaque blocks
# r g and b are from 0 to 9 for intensity

block.55498 = minecraft:end_portal minecraft:end_gateway


block.44852 = minecraft:fire minecraft:torch minecraft:wall_torch minecraft:campfire %minecraft:candle_cakes %minecraft:candles
block.24852 = minecraft:cave_vines:berries=true minecraft:light
block.44157 = minecraft:soul_fire minecraft:soul_torch minecraft:soul_wall_torch minecraft:soul_campfire
block.25984 = minecraft:redstone_lamp:lit=true minecraft:glowstone \
  minecraft:waxed_oxidized_copper_bulb:lit=true minecraft:oxidized_copper_bulb:lit=true minecraft:waxed_weathered_copper_bulb:lit=true minecraft:weathered_copper_bulb:lit=true minecraft:waxed_exposed_copper_bulb:lit=true minecraft:exposed_copper_bulb:lit=true minecraft:waxed_copper_bulb:lit=true minecraft:copper_bulb:lit=true

block.25941 = minecraft:lava minecraft:lava_cauldron
block.25951 = minecraft:shroomlight minecraft:magma_block


block.20000 = trial_spawner:trial_spawner_state=inactive
block.24322 = vault:vault_state=inactive
block.44985 = minecraft:trial_spawner:ominous=false minecraft:vault:ominous=false
block.45985 = minecraft:lantern minecraft:furnace:lit=true minecraft:blast_furnace:lit=true minecraft:smoker:lit=true minecraft:jack_o_lantern
block.45495 = %minecraft:lanterns minecraft:copper_torch minecraft:copper_wall_torch

block.44079 = minecraft:trial_spawner:ominous=true minecraft:vault:ominous=true
block.24984 = minecraft:brewing_stand
block.24777 = minecraft:beacon minecraft:end_rod

block.25498 = minecraft:end_portal_frame minecraft:ender_chest
block.25838 = minecraft:dragon_egg minecraft:crying_obsidian minecraft:respawn_anchor:charges=1,2,3,4

block.24809 = minecraft:nether_portal
block.24922 = minecraft:redstone_torch minecraft:redstone_wall_torch
block.25922 = minecraft:redstone_ore:lit=true
block.35035 = minecraft:sculk_sensor:sculk_sensor_phase=inactive minecraft:sculk_catalyst:bloom=false
block.35069= minecraft:sculk_sensor minecraft:sculk_catalyst
block.25589 = minecraft:sea_lantern minecraft:conduit
block.24297 = minecraft:sea_pickle:waterlogged=true
block.25687 = minecraft:enchanting_table
block.24565 = minecraft:glow_lichen minecraft:red_mushroom minecraft:brown_mushroom

block.34729 = minecraft:amethyst_cluster minecraft:large_amethyst_bud minecraft:small_amethyst_bud minecraft:medium_amethyst_bud minecraft:calibrated_sculk_sensor


block.25994 = minecraft:ochre_froglight
block.25595 = minecraft:verdant_froglight
block.25969 = minecraft:pearlescent_froglight

block.2777= minecraft:white_stained_glass minecraft:white_stained_glass_pane
block.2864= minecraft:orange_stained_glass minecraft:orange_stained_glass_pane
block.2747= minecraft:magenta_stained_glass minecraft:magenta_stained_glass_pane
block.2668= minecraft:light_blue_stained_glass minecraft:light_blue_stained_glass_pane
block.2873= minecraft:yellow_stained_glass minecraft:yellow_stained_glass_pane
block.2584= minecraft:lime_stained_glass minecraft:lime_stained_glass_pane
block.2867= minecraft:pink_stained_glass minecraft:pink_stained_glass_pane
block.2333= minecraft:gray_stained_glass minecraft:gray_stained_glass_pane
block.2555= minecraft:light_gray_stained_glass minecraft:light_gray_stained_glass_pane
block.2467= minecraft:cyan_stained_glass minecraft:cyan_stained_glass_pane
block.2648= minecraft:purple_stained_glass minecraft:purple_stained_glass_pane
block.2337= minecraft:blue_stained_glass minecraft:blue_stained_glass_pane
block.2752= minecraft:brown_stained_glass minecraft:brown_stained_glass_pane
block.2262= minecraft:green_stained_glass minecraft:green_stained_glass_pane
block.2722= minecraft:red_stained_glass minecraft:red_stained_glass_pane
block.2222= minecraft:black_stained_glass minecraft:black_stained_glass_pane

#//all things that start with 0 are treated as air, extra digits just category basically


#the following have subsurface properties
block.10015 = %minecraft:leaves
block.0015 = %minecraft:crops %minecraft:flowers %minecraft:edible_for_sheep minecraft:sugar_cane minecraft:tall_grass minecraft:tall_grass minecraft:leaf_litter minecraft:kelp_plant

block.0001 = minecraft:redstone_wire
block.0002 = minecraft:lever %minecraft:buttons
block.0003 = %minecraft:replaceable
block.0004 = minecraft:glass
