#include "/lib/settings.glsl"

iris.features.required = CUSTOM_IMAGES BLOCK_EMISSION_ATTRIBUTE COMPUTE_SHADERS
oldLighting=true

shadow.enabled=true
shadowTranslucent=true

shadowEntities=false
shadowPlayer=false
shadowBlockEntities=false

skipAllRendering=false
voxelizeLightBlocks=true

#define VOX_SIZE 18
#define VOX_SIZE_BIG 1800

occlusion.culling=true
image.worldVox = worldVoxSampler rgba_integer RGBA8UI unsigned_byte true false VOX_SIZE VOX_SIZE VOX_SIZE
#image.lightVox = lightVoxSampler rgba_integer RGBA32UI unsigned_int false false 18 18 18
image.lightVox = lightVoxSampler rgba_integer RGBA32UI unsigned_int false false VOX_SIZE VOX_SIZE VOX_SIZE_BIG
allowConcurrentCompute = false

const int shadowMapResolution = 0;
const float voxelDistance = 160.0;
const float shadowDistance = voxelDistance;
shadow.culling = reversed;

screen = [DEBUG] VOX_LAYERS
screen.DEBUG = DEBUG_OCCLUSION_MAP UNFLIP_DEBUG_MAPS DEBUG_OUTLINE_WIDTH DEBUG_AXIS

