#include "/lib/settings.glsl"

iris.features.required = CUSTOM_IMAGES BLOCK_EMISSION_ATTRIBUTE COMPUTE_SHADERS SSBO
oldLighting=true

shadow.enabled=true
shadowTranslucent=true

shadowEntities=false
shadowPlayer=false
shadowBlockEntities=false

skipAllRendering=false
voxelizeLightBlocks=true

#define VOX_SIZE 66
#define VOX_SIZE_BIG 1000
#define WORLD_VOX_SIZE_BIG 66

occlusion.culling=true
image.worldVox = worldVoxSampler rgba_integer RGBA8UI unsigned_byte true false VOX_SIZE VOX_SIZE WORLD_VOX_SIZE_BIG
#image.lightVox = lightVoxSampler rgba_integer RGBA32UI unsigned_int false false 18 18 18
image.lightVox = lightVoxSampler rgba_integer RGBA32UI unsigned_int false false VOX_SIZE VOX_SIZE VOX_SIZE_BIG
bufferObject.0=1024
bufferObject.1=12

indirect.prepare10 = 1 0

#yea doesnt really do anthing
allowConcurrentCompute = false

shadow.culling = reversed

screen.DebugStyle = UNFLIP_DEBUG_MAPS DEBUG_OUTLINE_WIDTH DEBUG_DECOLOR
screen.Misc = PRIDE_LIGHTING gap PARALLEL_UNPACK SHORTLISTED_COMPARISON AXES_INORDER
screen.Debug = DEBUG_OCCLUSION_MAP [DebugStyle] DEBUG_GRID_OUTLINE DEBUG_AXIS \
  EVERYTHING_IS_THE_SUN EVERYTHING_FACING_SRC KEEP_FULLY_OCCLUDED_SAMPLES DEBUG_SHOW_UPDATES DEBUG_UPDATES_INTENSITY\
  UNOCCLUDED_INTO_BLOCKS DEBUG_SCALE LIGHT_SOURCES_BLOCK_CENTERIC

screen = [Debug] [Misc] VOX_LAYERS COLORED_TRANSLUCENTS PENUMBRA_WIDTH PENUMBRAS_ENABLED UPDATE_STRIDE LIGHTING_RENDERSCALE

blend.gbuffers_entities.colortex4 = off
blend.gbuffers_hand.colortex4 = off

#colortex0 is albedo, colortex4 is normal, colortex5 is lighting