#define SHADERS_PROPERTIES

iris.features.required = CUSTOM_IMAGES BLOCK_EMISSION_ATTRIBUTE COMPUTE_SHADERS SSBO
oldLighting=true

shadow.enabled=true
shadowTranslucent=true

shadowEntities=false
shadowPlayer=false
shadowBlockEntities=false

skipAllRendering=false
voxelizeLightBlocks=true

#define VOX_SIZE 66
#define VOX_SIZE_BIG 1000
#define WORLD_VOX_SIZE_BIG 66

occlusion.culling=true
image.worldVox = worldVoxSampler rgba_integer RGBA8UI unsigned_byte true false VOX_SIZE VOX_SIZE WORLD_VOX_SIZE_BIG
#image.lightVox = lightVoxSampler rgba_integer RGBA32UI unsigned_int false false 18 18 18
image.lightVox = lightVoxSampler rgba_integer RGBA32UI unsigned_int false false VOX_SIZE VOX_SIZE VOX_SIZE_BIG
bufferObject.0=1024
bufferObject.1=12

indirect.prepare10 = 1 0

#yea doesnt really do anthing
allowConcurrentCompute = false

shadow.culling = reversed

screen.DebugStyle = UNFLIP_DEBUG_MAPS DEBUG_OUTLINE_WIDTH DEBUG_DECOLOR
screen.Misc = PRIDE_LIGHTING gap PARALLEL_UNPACK SHORTLISTED_COMPARISON AXES_INORDER
screen.Debug = DEBUG_OCCLUSION_MAP [DebugStyle] DEBUG_GRID_OUTLINE DEBUG_AXIS \
  EVERYTHING_IS_THE_SUN EVERYTHING_FACING_SRC KEEP_FULLY_OCCLUDED_SAMPLES DEBUG_SHOW_UPDATES DEBUG_UPDATES_INTENSITY\
  UNOCCLUDED_INTO_BLOCKS DEBUG_SCALE LIGHT_SOURCES_BLOCK_CENTERIC DEBUG_WHITEN DEBUG_WHITE_LEVEL
screen.LightSystem = VOX_LAYERS COLORED_TRANSLUCENTS PENUMBRA_WIDTH PENUMBRAS_ENABLED UPDATE_STRIDE

screen.Fog = VOLUMETRIC_FOG_SAMPLES FOG_DITHER_METHOD FOG_DENSITY FOG_BRIGHTNESS MAX_FOG_DEPTH FOG_TEMPORAL_NOISE FOG_BLUR

screen = [LightSystem] [Fog] [Debug] [Misc] LIGHTING_RENDERSCALE BLOOM_INTENSITY BLOOM_WIDTH

sliders = LIGHTING_RENDERSCALE BLOOM_WIDTH \
DEBUG_OUTLINE_WIDTH DEBUG_GRID_OUTLINE DEBUG_AXIS DEBUG_UPDATES_INTENSITY DEBUG_SCALE DEBUG_WHITE_LEVEL \
VOX_LAYERS PENUMBRA_WIDTH UPDATE_STRIDE \
VOLUMETRIC_FOG_SAMPLES FOG_DENSITY FOG_BRIGHTNESS MAX_FOG_DEPTH FOG_BLUR \
BLOOM_INTENSITY

blend.gbuffers_entities.colortex4 = off
blend.gbuffers_hand.colortex4 = off
blend.composite3.colortex6 = off
blend.composite4.colortex6 = off

#if BLOOM_INTENSITY==-1
program.composite3.enabled=false
program.composite4.enabled=false
#endif

#if FOG_BLUR<2
program.composite6.enabled=false
#endif